# Credenciales sensibles
oracle.db.username=ADMIN
oracle.db.password=Papagallo19.

# Configuración de Azure AD / MSAL - Valores sensibles
azure.activedirectory.client-id=5c98f65f-6472-404c-81b1-20bf3f69a706
azure.activedirectory.client-secret=df1a4c80-ad59-4cac-9dc8-3510d3d9a817
azure.activedirectory.tenant-id=5497f70a-565c-40b7-92c7-b62049f8638f

# Configuración de OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://azurecnsum1.b2clogin.com/5497f70a-565c-40b7-92c7-b62049f8638f/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://azurecnsum1.b2clogin.com/azurecnsum1.onmicrosoft.com/discovery/v2.0/keys?p=B2C_1_signupsignin