spring.application.name=usuarios
server.port=8082
server.servlet.context-path=/api
spring.config.import=classpath:application-secrets.properties
# Configuración de la base de datos Oracle con Wallet
spring.datasource.url=jdbc:oracle:thin:@c3cq5y7aelcsqgmu_medium?TNS_ADMIN=./Wallet_C3CQ5Y7AELCSQGMU&oracle.net.ssl_server_dn_match=false
spring.datasource.username=${ORACLE_DB_USERNAME}
spring.datasource.password=${ORACLE_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# Configuración de logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.rabbithole=DEBUG

# Configuración de Azure AD / MSAL - Los valores sensibles están en application-secrets.properties
azure.activedirectory.client-id = ${AZURE_ACTIVEDIRECTORY_CLIENT_ID}
azure.activedirectory.client-secret = ${AZURE_ACTIVEDIRECTORY_CLIENT_SECRET}
azure.activedirectory.tenant-id = ${AZURE_ACTIVEDIRECTORY_TENANT_ID}

# Configuración de OAuth2 Resource Server - Los valores están en application-secrets.properties
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}
